package pm_cli_test;

import static javax.xml.ws.BindingProvider.ENDPOINT_ADDRESS_PROPERTY;

import java.io.FileInputStream;
import java.io.InputStream;
import java.security.KeyStore;
import java.util.Base64;
import java.util.Map;

import javax.xml.registry.JAXRException;
import javax.xml.ws.BindingProvider;

import org.junit.*;

import pm.cli.Client;
import pm.exception.cli.AlreadyExistsLoggedUserException;
// classes generated by wsimport from WSDL
import pm.ws.*;// classes generated from WSDL
import pt.ulisboa.tecnico.seconf.ws.uddi.UDDINaming;


/**
 * Integration Test suite
 */
public class Client_Test {

    private static KeyStore ks;
    private static Client c;
    
    private static String alias = "client";
    private static char[] password = "benfica".toCharArray();
    
    // tests
    // assertEquals(expected, actual);

    // public void createDoc(CreateDoc parameters) throws
    // DocAlreadyExists_Exception

    @BeforeClass
    public static void oneTimeSetUp() throws JAXRException {
        // ********** Connection to Server ********** //
        String url = "http://localhost:8080/pm-ws/endpoint";
        String name = "pm-ws";
        String uddiURL = "http://localhost:9090";
        
        UDDINaming uddiNaming = new UDDINaming(uddiURL);
        String endpointAddress = uddiNaming.lookup(name);
        PasswordManagerImplService service = new PasswordManagerImplService();
        PasswordManager port = service.getPasswordManagerImplPort();
        BindingProvider bindingProvider = (BindingProvider) port;
        Map<String, Object> requestContext = bindingProvider.getRequestContext();
        requestContext.put(ENDPOINT_ADDRESS_PROPERTY, endpointAddress);
        // ********** Open Keystore **************** //
        try{
            ks = KeyStore.getInstance("JKS");
            InputStream readStream = new FileInputStream("src/main/resources/KeyStore.jks");
            ks.load(readStream, password);
            readStream.close();
        }catch(Exception e){
            System.out.println("Something wrong with keystore!");
        }
        // ****************************
        c = new Client(port);
        
    }

    @AfterClass
    public static void oneTimeTearDown() {
        c.close();
        c = null;
    }
    //************************************************\\
    //                Reborn's Tests                  \\
    //************************************************\\
    @Test
    public void testClient() throws Exception {

        c.init(ks, alias, password);
        c.register_user();
        c.save_password("facebook.com".getBytes(), "reborn".getBytes(), "reborn_pwd".getBytes());
        c.retrieve_password("facebook.com".getBytes(), "reborn".getBytes());
        c.close();
    }

    @Test(expected = AlreadyExistsLoggedUserException.class)
    public void testInvalidInit() throws Exception {
        c.init(ks,alias,password);
        c.init(null, null, null);
    }

    @Test(expected = Exception.class) //A corrigir
    public void testRegisterUser_InvalidKey() throws Exception {
        c.init(null, alias, password);
        c.register_user();
    }
    
    @Test(expected = Exception.class) //A corrigir
    public void testRegisterUser_KeyAlreadyExists() throws Exception {
        c.init(ks, alias, password);
        c.init(ks, alias, "reborn_pwd".toCharArray());
        c.register_user();
    }

    @Test(expected = Exception.class) //A corrigir
    public void testSavePasswordInvalidDomain() throws Exception {
        c.init(ks, alias, password);
        c.save_password(null, "reborn".getBytes(), "reborn_pwd".getBytes());
    }
    
    //@Test(expected = Exception.class) //A corrigir
    //public void testSavePasswordInvalidDomain_1() throws Exception {
    //    c.init(ks, alias, password);
    //    c.save_password("".getBytes(), "reborn".getBytes(), "reborn_pwd".getBytes());
    //}
    
    @Test(expected = Exception.class) //A corrigir
    public void testSavePasswordInvalidUsername() throws Exception {
        c.init(ks, alias, password);
        c.save_password("facebook.com".getBytes(), null, "reborn_pwd".getBytes());
    }
    //@Test(expected = Exception.class) //A corrigir
    //public void testSavePasswordInvalidUsername_1() throws Exception {
    //    c.init(ks, alias, password);
    //    c.save_password("facebook.com".getBytes(), "".getBytes(), "reborn_pwd".getBytes());
    //}
    
    @Test(expected = Exception.class) //A corrigir
    public void testRetrievePasswordInvalidDomain() throws Exception {
        c.init(ks, alias, password);
        c.save_password("facebook.com".getBytes(), "reborn".getBytes(), "reborn_pwd".getBytes());
        c.retrieve_password(null, "reborn".getBytes());
    }
    //@Test(expected = Exception.class) //A corrigir
    //public void testRetrievePasswordInvalidDomain_1() throws Exception {
    //    c.init(ks, alias, password);
    //    c.save_password("facebook.com".getBytes(), "reborn".getBytes(), "reborn_pwd".getBytes());
    //    c.retrieve_password("".getBytes(), "reborn".getBytes());
    //}

    @Test(expected = Exception.class) //A corrigir
    public void testRetrievePasswordInvalidUsername() throws Exception {
        c.init(ks, alias, password);
        c.save_password("facebook.com".getBytes(), "reborn".getBytes(), "reborn_pwd".getBytes());
        c.retrieve_password("facebook.com".getBytes(), null);
    }
//    @Test(expected = Exception.class) //A corrigir
//    public void testRetrievePasswordInvalidUsername_1() throws Exception {
//        c.init(ks, alias, password);
//        c.save_password("facebook.com".getBytes(), "reborn".getBytes(), "reborn_pwd".getBytes());
//        c.retrieve_password("facebook.com".getBytes(), "".getBytes());
//    }
}
