package pm_cli_test;

import static javax.xml.ws.BindingProvider.ENDPOINT_ADDRESS_PROPERTY;

import java.io.FileInputStream;
import java.io.InputStream;
import java.security.KeyStore;
import java.util.Base64;
import java.util.Map;

import javax.xml.registry.JAXRException;
import javax.xml.ws.BindingProvider;

import org.junit.*;

import pm.cli.Client;
import pm.cli.ClientLib;
import pm.exception.cli.AlreadyExistsLoggedUserException;
// classes generated by wsimport from WSDL
import pm.ws.*;// classes generated from WSDL
import pt.ulisboa.tecnico.seconf.ws.uddi.UDDINaming;


/**
 * Integration Test suite
 */
public class Client_Test {

    private static ClientLib c;
    private static String alias = "client";
    
    // tests
    // assertEquals(expected, actual);

    // public void createDoc(CreateDoc parameters) throws
    // DocAlreadyExists_Exception

    @BeforeClass
    public static void oneTimeSetUp() throws JAXRException {
        // ********** Connection to Server ********** //
        String url = "http://localhost:8080/pm-ws/endpoint";
        String name = "pm-ws";
        String uddiURL = "http://localhost:9090";
        
        UDDINaming uddiNaming = new UDDINaming(uddiURL);
        String endpointAddress = uddiNaming.lookup(name);
        PasswordManagerImplService service = new PasswordManagerImplService();
        PasswordManager port = service.getPasswordManagerImplPort();
        BindingProvider bindingProvider = (BindingProvider) port;
        Map<String, Object> requestContext = bindingProvider.getRequestContext();
        requestContext.put(ENDPOINT_ADDRESS_PROPERTY, endpointAddress);
        // ********** Open Keystore **************** //
        
        // ****************************
        c = new ClientLib(port);
        
    }
    
    public KeyStore getKeyStore(String fileName,char[] passwd){
        KeyStore k = null;
        try{
            k = KeyStore.getInstance("JKS");
            InputStream readStream = new FileInputStream("src/main/resources/"+fileName+".jks");
            k.load(readStream, passwd);
            readStream.close();
        }catch(Exception e){
            System.out.println("Test Failed");
            e.printStackTrace();
        }
        return k;
    }

    @AfterClass
    public static void oneTimeTearDown() {
        c.close();
    }
    //************************************************\\
    //                Reborn's Tests                  \\
    //************************************************\\
    @Test
    public void testClient() throws Exception {
        char[] password = "seconf".toCharArray();
        KeyStore ks = getKeyStore("KeyStore-seconf",password);

        c.init(ks, alias, password);
        c.register_user();
        c.save_password("facebook.com".getBytes(), "reborn".getBytes(), "reborn_pwd".getBytes());
        c.retrieve_password("facebook.com".getBytes(), "reborn".getBytes());
        c.close();
    }

    @Test(expected = AlreadyExistsLoggedUserException.class)
    public void testInvalidInit() throws Exception {
        char[] password = "benfica".toCharArray();
        KeyStore ks = getKeyStore("KeyStore","benfica".toCharArray());
        c.init(ks,alias,password);
        c.init(null, null, null);
    }

    @Test(expected = Exception.class) //A corrigir
    public void testRegisterUser_InvalidKey() throws Exception {
        c.init(null, alias, "hi".toCharArray());
        c.register_user();
    }
    
    @Test(expected = Exception.class) //A corrigir
    public void testRegisterUser_KeyAlreadyExists() throws Exception {
        char[] password = "reborn".toCharArray();
        KeyStore ks = getKeyStore("KeyStore-reborn",password);
        c.init(ks, alias, password);
        c.register_user();
        c.register_user();
    }

    @Test(expected = Exception.class) //A corrigir NÂO ESTÀ A FUNCIONAR!!
    public void testSavePasswordInvalidDomain() throws Exception {
        char[] password = "luisrafael".toCharArray();
        KeyStore ks = getKeyStore("KeyStore-luisrafael",password);
        c.init(ks, alias, password);
        c.save_password(null, "reborn".getBytes(), "reborn_pwd".getBytes());
    }
    
    //@Test(expected = Exception.class) //A corrigir
    //public void testSavePasswordInvalidDomain_1() throws Exception {
    //    char[] password = "antonio".toCharArray();
    //    KeyStore ks = getKeyStore("KeyStore-antonio",password);
    //    c.init(ks, alias, password);
    //    c.save_password("".getBytes(), "reborn".getBytes(), "reborn_pwd".getBytes());
    //}
    
    @Test(expected = Exception.class) //A corrigir NÂO ESTÀ A FUNCIONAR!!
    public void testSavePasswordInvalidUsername() throws Exception {
        char[] password = "pedrofran".toCharArray();
        KeyStore ks = getKeyStore("KeyStore-pedrofran",password);
        c.init(ks, alias, password);
        c.save_password("facebook.com".getBytes(), null, "reborn_pwd".getBytes());
    }
    //@Test(expected = Exception.class) //A corrigir
    //public void testSavePasswordInvalidUsername_1() throws Exception {
    //    char[] password = "augusto".toCharArray();
    //    KeyStore ks = getKeyStore("KeyStore-augusto", password);
    //    c.init(ks, alias, password);
    //    c.save_password("facebook.com".getBytes(), "".getBytes(), "reborn_pwd".getBytes());
    //}
    
    @Test(expected = Exception.class) //InvalidKeyUsed Error instead of Domain
    public void testRetrievePasswordInvalidDomain() throws Exception {
        char[] password = "alberto".toCharArray();
        KeyStore ks = getKeyStore("KeyStore-alberto",password);
        c.init(ks, alias, password);
        c.save_password("facebook.com".getBytes(), "alberto".getBytes(), "alberto".getBytes());
        c.retrieve_password(null, "alberto".getBytes());
    }
    //@Test(expected = Exception.class) //A corrigir
    //public void testRetrievePasswordInvalidDomain_1() throws Exception {
    //    char[] password = "adolfo".toCharArray();
    //    KeyStore ks = getKeyStore("KeyStore-adolfo",password);
    //    c.init(ks, alias, password);
    //    c.save_password("facebook.com".getBytes(), "reborn".getBytes(), "reborn_pwd".getBytes());
    //    c.retrieve_password("".getBytes(), "reborn".getBytes());
    //}

    @Test(expected = Exception.class) //A corrigir INVALIDKEY Used
    public void testRetrievePasswordInvalidUsername() throws Exception {
        char[] password = "alejandro".toCharArray();
        KeyStore ks = getKeyStore("KeyStore-alejandro",password);
        c.init(ks, alias, password);
        c.save_password("facebook.com".getBytes(), "reborn".getBytes(), "reborn_pwd".getBytes());
        c.retrieve_password("facebook.com".getBytes(), null);
    }
//    @Test(expected = Exception.class) //A corrigir
//    public void testRetrievePasswordInvalidUsername_1() throws Exception {
//        char[] password = "ferrari".toCharArray();
//        KeyStore ks = getKeyStore("KeyStore-ferrari","ferrari".toCharArray());
//        c.init(ks, alias, password);
//        c.save_password("facebook.com".getBytes(), "reborn".getBytes(), "reborn_pwd".getBytes());
//        c.retrieve_password("facebook.com".getBytes(), "".getBytes());
//    }
}
