//package sdstore_test;
//
//
//
//import javax.xml.registry.JAXRException;
//
//import org.junit.*;
//
//import example.cli.*;
//// classes generated by wsimport from WSDL
//import pt.ulisboa.tecnico.sdis.store.ws.*;
//
//
///**
// * Integration Test suite
// */
//public class StoreIT {
//
//	private static SecurityLayer STORE_CLIENT;
//    // tests
//    // assertEquals(expected, actual);
//
//    // public void createDoc(CreateDoc parameters) throws
//    // DocAlreadyExists_Exception
//
//    @BeforeClass
//    public static void oneTimeSetUp() throws JAXRException {
//        FrontEnd service = new FrontEnd("http://localhost:8081", "SD-STORE", 3, 2, 2, 1000);
//        STORE_CLIENT = new SecurityLayer (service);
//    }
//
//    @AfterClass
//    public static void oneTimeTearDown() {
//    	STORE_CLIENT = null;
//    }
//    @Test
//    public void testStore() throws Exception {
//        final DocUserPair docUser = new DocUserPair();
//        docUser.setDocumentId("c1");
//        docUser.setUserId("carla");
//
//        STORE_CLIENT.createDoc(docUser);
//
//        STORE_CLIENT.store(docUser, "c1contents".getBytes());
//        byte[] a = "".getBytes();
//    }
//
//    @Test
//    public void testStoreNullContent() throws Exception {
//        final DocUserPair docUser = new DocUserPair();
//        docUser.setDocumentId("j1");
//        docUser.setUserId("Joana");
//
//        STORE_CLIENT.createDoc(docUser);
//
//        STORE_CLIENT.store(docUser, null);
//    }
//
//    @Test(expected = DocDoesNotExist_Exception.class)
//    public void testDocDoesNotExist() throws Exception {
//        final DocUserPair docUser = new DocUserPair();
//        docUser.setDocumentId("c2");
//        docUser.setUserId("carla");
//
//        STORE_CLIENT.store(docUser, "c2contents".getBytes());
//    }
//
//    @Test(expected = DocDoesNotExist_Exception.class)
//    public void testStoreNullDoc() throws Exception {
//        final DocUserPair docUser = new DocUserPair();
//        docUser.setDocumentId(null);
//        docUser.setUserId("carla");
//
//        STORE_CLIENT.store(docUser, "c2contents".getBytes());
//    }
//
//    @Test(expected = DocDoesNotExist_Exception.class)
//    public void testStoreEmptyDoc() throws Exception {
//        final DocUserPair docUser = new DocUserPair();
//        docUser.setDocumentId("");
//        docUser.setUserId("carla");
//
//        STORE_CLIENT.store(docUser, "c2contents".getBytes());
//    }
//
//    @Test(expected = UserDoesNotExist_Exception.class)
//    public void testUserDoesNotExist() throws Exception {
//        final DocUserPair docUser = new DocUserPair();
//        docUser.setDocumentId("c3");
//        docUser.setUserId("userthatdoesnotexist");
//
//        STORE_CLIENT.store(docUser, "c3contents".getBytes());
//    }
//
//    @Test(expected = UserDoesNotExist_Exception.class)
//    public void testStoreNullUser() throws Exception {
//        final DocUserPair docUser = new DocUserPair();
//        docUser.setDocumentId("c3");
//        docUser.setUserId(null);
//
//        STORE_CLIENT.store(docUser, "c3contents".getBytes());
//    }
//
//    @Test(expected = UserDoesNotExist_Exception.class)
//    public void testStoreEmptyUser() throws Exception {
//        final DocUserPair docUser = new DocUserPair();
//        docUser.setDocumentId("c3");
//        docUser.setUserId("");
//
//        STORE_CLIENT.store(docUser, "c3contents".getBytes());
//    }
//    /*
//    @Test(expected = CapacityExceeded_Exception.class)
//    public void testOverCapacity() throws Exception {
//        final DocUserPair docUser = new DocUserPair();
//        docUser.setDocumentId("e1");
//        docUser.setUserId("eduardo");
//
//        STORE_CLIENT.createDoc(docUser);
//
//        byte[] contents = new byte[(10 * 1024) + 1];
//        for (int idx = 0; idx < contents.length; idx++)
//            contents[idx] = (byte) 1;
//
//        STORE_CLIENT.store(docUser, contents);
//    }
//
//    @Test
//    public void testStoreReplaceFullCapacity() throws Exception {
//        final DocUserPair docUser = new DocUserPair();
//        docUser.setDocumentId("m1");
//        docUser.setUserId("manuel");
//
//        STORE_CLIENT.createDoc(docUser);
//
//        byte[] content1 = new byte[10 * 1024];
//        for (int idx = 0; idx < content1.length; idx++)
//            content1[idx] = (byte) 1;
//
//        STORE_CLIENT.store(docUser, content1);
//
//        byte[] content2 = new byte[1];
//        content2[0] = (byte) 1;
//
//        STORE_CLIENT.store(docUser, content2);
//    }
//
//    @Test
//    public void testStoreReplaceWithFullCapacityDoc() throws Exception {
//        final DocUserPair docUser = new DocUserPair();
//        docUser.setDocumentId("j1");
//        docUser.setUserId("jonas");
//
//        STORE_CLIENT.createDoc(docUser);
//
//        byte[] content1 = new byte[1];
//        content1[0] = (byte) 1;
//
//        STORE_CLIENT.store(docUser, content1);
//
//        byte[] content2 = new byte[10 * 1024];
//        for (int idx = 0; idx < content2.length; idx++)
//            content2[idx] = (byte) 1;
//
//        STORE_CLIENT.store(docUser, content2);
//
//    }*/
//
//}
